sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache: npm
branches:
  only:
    - hexo # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: DTw3KHJslUFsAluMD99FDVcs2m9rSoN29iqSZNtjKeensxrI/2taw9VaY3i67zW2Y/4KaRjMKc2lCM9z0v6T5NUpbNisEfoBLZru1FjiqQ8Vz2+GRdjDIP1ibjTcUEX49sk4IhRIrH7CK0v+GSBegpwP4GWd3FvHRAWRkAfNbPS0onj7I71SjyWCyfIigEW45rXwcjv0NRuLuVY7TAMfyIIoGU7wtg+Fw/F0CKl/2R+ODxdlup2AqMue7h3yfV0XVkVJxl3feuyAMD+FPTa5xjmed3nzykJZB86ncKmVLsVnC+mFJXRB2li9mq6xtt1emU+bNzxsJHK0eyAGeSvk7Z3A1fOltAUf4oZMRudAFpgFPNpWl8DAVNoKRRkHCJ/1gCNUbqpGzMV9c9LxU/PRYmdzjPgd5qe4DB0WgK6rtPrc7qELhl/A8sPzglBuW7m5ju+BpQwAV1GALNO01hF9nEktCNBi2fqjFLNIFoCkOhfvWHChWbUHM7fQl+unHqTy4zIyGmWlSDlzVwhZPV3skBFtlxTYgxb901DeznDE984gcXtEyb9M+/MP84RtMHXHm/GeOnL5fLf3L1IkEHhZpMMuVBAkXGX6GNcjv7Lv51xvs6ZJp7eTjVlRkCqlSlkgtN2ZJFQMgTEr3cNTz2SGaHeaB0fKC8NdrH9BlgCNctI=
  keep-history: true
  on:
    branch: master
  local-dir: public
